version: "3.9"

x-shared-environment: &shared-env
  environment:
    INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
    INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
    INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
    INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
    INFISICAL_URL: ${INFISICAL_URL}
    TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-false}
    TELEMETRY_ENDPOINT: ${TELEMETRY_URL:-None}

services:
  rag_backend:
    image: ghcr.io/chidirnweke/chatgitpt-backend:latest
    container_name: rag_backend
    <<: *shared-env
    depends_on:
      - startup_container
    command:
      [
        "poetry",
        "run",
        "fastapi",
        "run",
        "src/talkingcode/backend/main.py",
        "--workers",
        "2",
        "--port",
        "8000",
      ]
    networks:
      - postgres_network
      - qdrant_network
      - reverse-proxy
      - telemetry-network

  startup_container:
    container_name: rag_backend_startup_container
    image: ghcr.io/chidirnweke/chatgitpt-backend:latest
    restart: "no"
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    networks:
      - telemetry-network
      - postgres_network
    <<: *shared-env

networks:
  reverse-proxy:
    external: true
  telemetry-network:
    external: true
  postgres_network:
    external: true
  qdrant_network:
    external: true
