version: "3.9"

x-shared-environment: &shared-env
  environment:
    INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
    INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
    INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
    INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
    INFISICAL_URL: ${INFISICAL_URL}
    TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-false}
    TELEMETRY_ENDPOINT: ${TELEMETRY_ENDPOINT:-None}
    INFISICAL_ENABLED: ${INFISICAL_ENABLED:-false}

services:
  rag_backend:
    image: ghcr.io/chidirnweke/talkingcode-backend:latest
    container_name: rag_backend
    <<: *shared-env
    depends_on:
      - startup_container
    healthcheck:
      test: curl -f http://localhost:8000/v1/api/health || exit 1
      interval: 600s
      timeout: 5s
      retries: 3
      start_period: 10s
    command:
      [
        "poetry",
        "run",
        "fastapi",
        "run",
        "src/talkingcode/backend/main.py",
        "--workers",
        "2",
        "--port",
        "8000",
      ]
    networks:
      - postgres-network
      - qdrant-network
      - reverse-proxy
      - telemetry-network

  startup_container:
    container_name: rag_backend_startup_container
    image: ghcr.io/chidirnweke/talkingcode-backend:latest
    restart: "no"
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    networks:
      - telemetry-network
      - postgres-network
    <<: *shared-env

networks:
  reverse-proxy:
    external: true
  telemetry-network:
    external: true
  postgres-network:
    external: true
  qdrant-network:
    external: true
