version: "3.8"
services:
  rag_backend:
    image: ghcr.io/chidirnweke/chatgitpt-backend:latest
    container_name: rag_backend
    environment:
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - CHAT_MODEL=${CHAT_MODEL}
      - OPENAI_EMBEDDING_API_KEY=${OPENAI_EMBEDDING_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - ASYNC_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - TOP_K=${TOP_K:-5}
      - MAX_SPEND=${MAX_TOKENS:-1.5}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - chatGITpt_network
      - app_network

networks:
  chatGITpt_network:
    driver: bridge
    name: chatGITpt_network
  app_network:
    external: true
