version: "3.9"

x-shared-environment: &shared-env
  environment:
    INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
    INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
    INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
    INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
    INFISICAL_URL: ${INFISICAL_URL}
    TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-false}
    TELEMETRY_ENDPOINT: ${TELEMETRY_ENDPOINTs:-None}
    INFISICAL_ENABLED: ${INFISICAL_ENABLED:-false}

services:
  data_pipelines:
    container_name: talkingcode_data_pipelines
    image: ghcr.io/chidirnweke/talkingcode-data_pipelines:latest
    depends_on:
      - startup_container
    networks:
      - telemetry-network
      - postgres-network
      - qdrant-network
    <<: *shared-env

  startup_container:
    container_name: talkingcode_startup_container
    image: ghcr.io/chidirnweke/talkingcode-data_pipelines:latest
    restart: "no"
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    networks:
      - telemetry-network
      - postgres-network
    <<: *shared-env

networks:
  telemetry-network:
    external: true
  postgres-network:
    external: true
  qdrant-network:
    external: true
