site_name: ChatGITpt backend documentation

theme:
  name: "material"

plugins: 
  - search
  - render_swagger
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
          options:
            docstring_style: google
          import:
            - https://docs.python.org/3/objects.inv
