"""Add primary key to languages_repository_bridge

Revision ID: 2b7a131f5366
Revises: a3d2ba8fd39d
Create Date: 2024-09-21 21:20:53.151361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2b7a131f5366'
down_revision: Union[str, None] = 'a3d2ba8fd39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages_repository_bridge', 'language_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('languages_repository_bridge', 'repository_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('languages_repository_bridge', 'repository_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages_repository_bridge', 'repository_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('languages_repository_bridge', 'repository_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('languages_repository_bridge', 'language_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
