"""Use int pipeline key for pipeline metadata

Revision ID: c5bec2fa5353
Revises: da6003284020
Create Date: 2025-03-30 13:22:40.575523

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5bec2fa5353"
down_revision: Union[str, None] = "da6003284020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_runs") as batch_op:
        batch_op.alter_column(
            "associated_schedule",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Integer(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_runs") as batch_op:
        batch_op.alter_column(
            "associated_schedule",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
