"""Pipeline database models

Revision ID: da6003284020
Revises: e21b39f61c1e
Create Date: 2025-03-29 20:19:48.474155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da6003284020"
down_revision: Union[str, None] = "e21b39f61c1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_start_time", sa.DateTime(), nullable=False),
        sa.Column("start_hour", sa.Integer(), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("associated_schedule", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["associated_schedule"],
            ["pipeline_schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_runs")
    op.drop_table("pipeline_schedule")
    # ### end Alembic commands ###
