"""Add pipeline models

Revision ID: e21b39f61c1e
Revises: b7787d05b1ca
Create Date: 2025-03-29 19:03:03.973809

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e21b39f61c1e"
down_revision: Union[str, None] = "b7787d05b1ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_repositories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("name", "user"),
    )
    op.create_table(
        "github_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content_url", sa.String(length=255), nullable=False),
        sa.Column("sha", sa.String(length=255), nullable=False),
        sa.Column("repository_name", sa.String(length=255), nullable=False),
        sa.Column("repository_user", sa.String(length=255), nullable=False),
        sa.Column("file_extension", sa.String(length=255), nullable=False),
        sa.Column("path_in_repo", sa.String(length=255), nullable=False),
        sa.Column("latest_version", sa.Boolean(), nullable=False),
        sa.Column("is_embedded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_name", "repository_user"],
            ["github_repositories.name", "github_repositories.user"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_files")
    op.drop_table("github_repositories")
    # ### end Alembic commands ###
