"""Initialize schema

Revision ID: 225c46538c5f
Revises:
Create Date: 2024-12-28 13:14:03.050467

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "225c46538c5f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_languages",
        sa.Column("language", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("language"),
    )
    op.create_table(
        "github_repositories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("name", "user"),
    )
    op.create_table(
        "tokens_spent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "github_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content_url", sa.String(length=255), nullable=False),
        sa.Column("sha", sa.String(length=255), nullable=False),
        sa.Column("repository_name", sa.String(length=255), nullable=False),
        sa.Column("repository_user", sa.String(length=255), nullable=False),
        sa.Column("file_extension", sa.String(length=255), nullable=False),
        sa.Column("path_in_repo", sa.String(length=255), nullable=False),
        sa.Column("latest_version", sa.Boolean(), nullable=False),
        sa.Column("is_embedded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_name", "repository_user"],
            ["github_repositories.name", "github_repositories.user"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "languages_repository_bridge",
        sa.Column("language_name", sa.String(length=255), nullable=False),
        sa.Column("repository_name", sa.String(length=255), nullable=False),
        sa.Column("repository_user", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_name"],
            ["github_languages.language"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_name", "repository_user"],
            ["github_repositories.name", "github_repositories.user"],
        ),
        sa.PrimaryKeyConstraint("language_name", "repository_name", "repository_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("languages_repository_bridge")
    op.drop_table("github_files")
    op.drop_table("tokens_spent")
    op.drop_table("github_repositories")
    op.drop_table("github_languages")
    # ### end Alembic commands ###
