"""Removed languages data

Revision ID: 35a0b68763e6
Revises: 225c46538c5f
Create Date: 2024-12-30 11:45:33.147508

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35a0b68763e6"
down_revision: Union[str, None] = "225c46538c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_languages")
    op.drop_table("languages_repository_bridge")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages_repository_bridge",
        sa.Column("language_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("repository_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("repository_user", sa.VARCHAR(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_name"],
            ["github_languages.language"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_name", "repository_user"],
            ["github_repositories.name", "github_repositories.user"],
        ),
        sa.PrimaryKeyConstraint("language_name", "repository_name", "repository_user"),
    )
    op.create_table(
        "github_languages",
        sa.Column("language", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("language"),
    )
    # ### end Alembic commands ###
