"""Remove token spend model from pipelines

Revision ID: bd6f350c26bc
Revises: 35a0b68763e6
Create Date: 2024-12-31 12:27:43.827939

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6f350c26bc"
down_revision: Union[str, None] = "35a0b68763e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens_spent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens_spent",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("token_count", sa.INTEGER(), nullable=False),
        sa.Column("model", sa.VARCHAR(length=255), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
