[tool.poetry]
name = "talkingcode-cli"
version = "0.1.0"
description = "CLI tool for managing TalkingCode - a GitHub code RAG system"
authors = ["ChidiRNweke <chidi125@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "talkingcode", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
talkingcode-pipelines = {path = "../pipelines"}
talkingcode-backend = {path = "../backend"}
talkingcode-shared = {path = "../shared"}
typer = {extras = ["all"], version = "^0.12.3"}
rich = {extras = ["all"], version = "^13.7.0"}
python-dotenv = "^1.0.1"
uvicorn = "^0.27.1"

[tool.poetry.scripts]
talkingcode = "talkingcode.cli.main:app"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"

[tool.ruff.lint]
extend-select = ["I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"