"""initial schema

Revision ID: d4c0865a4138
Revises: 
Create Date: 2026-02-22 18:32:52.249981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd4c0865a4138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('selected_model', sa.String(length=255), nullable=True),
    sa.Column('planner_model_used', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turn_conv_created', 'conversation_turns', ['conversation_id', 'created_at'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_repo_provider_owner_name')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('git_ref', sa.String(length=255), nullable=False),
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('symbols_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', 'git_ref', name='uq_document_repo_path_ref')
    )
    op.create_index('idx_document_repo_path', 'documents', ['repository_id', 'path'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_call_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('visible_args_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_turn_seq', 'tool_call_timeline', ['turn_id', 'sequence_no'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('symbols_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_index')
    )
    op.create_index('idx_chunk_area_type', 'document_chunks', ['area', 'file_type'], unique=False)
    op.create_index('idx_chunk_symbols', 'document_chunks', ['symbols_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_chunk_tags', 'document_chunks', ['tags_json'], unique=False, postgresql_using='gin')
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings')
    op.drop_index('idx_chunk_tags', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunk_symbols', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunk_area_type', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_timeline_turn_seq', table_name='tool_call_timeline')
    op.drop_table('tool_call_timeline')
    op.drop_table('ingestion_runs')
    op.drop_index('idx_document_repo_path', table_name='documents')
    op.drop_table('documents')
    op.drop_table('repositories')
    op.drop_index('idx_turn_conv_created', table_name='conversation_turns')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
