"""Use sha instead of last upgrade

Revision ID: 5eeed115fc03
Revises: 2b7a131f5366
Create Date: 2024-12-23 16:12:36.556234

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eeed115fc03"
down_revision: Union[str, None] = "2b7a131f5366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_files", "last_modified")
    op.add_column(
        "github_files", sa.Column("sha", sa.String(length=40), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_files", "sha")
    op.add_column(
        "github_files", sa.Column("last_modified", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###
