version: "3.8"
services:
  postgres:
    image: postgres:12
    env_file:
      - config/env.secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dagster:
    build: .
    env_file:
      - config.env
    volumes:
      - dagster_data:/dagster
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  dagster_data:
