version: "3.8"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatGITpt
    volumes:
      - postgres-data-chatGITpt-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data-chatGITpt-test:
