/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/agentic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Agentic
         * @description Agentic chat endpoint with SSE streaming.
         */
        post: operations["chat_agentic_chat_agentic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Timeline
         * @description Get chat timeline for conversation.
         */
        get: operations["get_chat_timeline_chat_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return curated model list with labels and default.
         */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repos
         * @description List all tracked repositories.
         */
        get: operations["list_repos_repos_get"];
        put?: never;
        /**
         * Register Repo
         * @description Register a GitHub repository for ingestion.
         */
        post: operations["register_repo_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/ingest-owned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Owned Repo Ingestion
         * @description Ingest all repositories owned by the authenticated user (excluding forks).
         */
        post: operations["start_owned_repo_ingestion_repos_ingest_owned_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repo
         * @description Get details of a specific repository.
         */
        get: operations["get_repo_repos__owner___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Ingestion
         * @description Start an ingestion run. Synchronous — completes when ingestion is done.
         */
        post: operations["start_ingestion_repos__owner___name__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingestion Runs
         * @description List ingestion run history for a repository.
         */
        get: operations["list_ingestion_runs_repos__owner___name__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatAgenticRequest
         * @description Request payload for agentic chat endpoint.
         */
        ChatAgenticRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Question
             * @default
             */
            question: string;
            /** Selected Model */
            selected_model?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRunInfo */
        IngestionRunInfo: {
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["IngestionStatus"];
        };
        /**
         * IngestionStatus
         * @description Ingestion run status.
         * @enum {string}
         */
        IngestionStatus: "running" | "done" | "failed";
        /**
         * ModelInfoResponse
         * @description Information about a chat model.
         */
        ModelInfoResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * ModelListResponse
         * @description Response model for model list endpoint.
         */
        ModelListResponse: {
            /** Default */
            default: string;
            /** Models */
            models: components["schemas"]["ModelInfoResponse"][];
        };
        /**
         * RegisterRepoRequest
         * @description Request body for registering a repository.
         */
        RegisterRepoRequest: {
            /**
             * Default Branch
             * @default main
             */
            default_branch: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
        };
        /** RepositoryInfo */
        RepositoryInfo: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Branch */
            default_branch: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Ingested At */
            last_ingested_at: string | null;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Provider */
            provider: string;
        };
        /**
         * StartIngestionRequest
         * @description Request body for starting an ingestion run.
         */
        StartIngestionRequest: {
            /** Git Ref */
            git_ref?: string | null;
        };
        /**
         * ToolCallInfoResponse
         * @description Information about a tool call in the timeline.
         */
        ToolCallInfoResponse: {
            /** Duration Ms */
            duration_ms: number | null;
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Tool Name */
            tool_name: string;
            /** Turn Id */
            turn_id: string;
            /** Visible Args */
            visible_args?: {
                [key: string]: unknown;
            };
        };
        /**
         * ToolTimelineResponse
         * @description Response model for tool timeline endpoint.
         */
        ToolTimelineResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Timeline */
            timeline: components["schemas"]["ToolCallInfoResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_agentic_chat_agentic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatAgenticRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_timeline_chat_timeline_get: {
        parameters: {
            query: {
                conversation_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    list_repos_repos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryInfo"][];
                };
            };
        };
    };
    register_repo_repos_post: {
        parameters: {
            query?: {
                api_key?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_owned_repo_ingestion_repos_ingest_owned_post: {
        parameters: {
            query?: {
                api_key?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartIngestionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_repos__owner___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ingestion_repos__owner___name__ingest_post: {
        parameters: {
            query?: {
                api_key?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartIngestionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_runs_repos__owner___name__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
