import asyncio
from html import escape
from typing import TYPE_CHECKING, AsyncGenerator, Optional, Protocol, Self, cast
from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionMessageParam, ChatCompletionChunk
from pydantic import BaseModel, model_validator
from dataclasses import dataclass
from errors import map_errors

if TYPE_CHECKING:
    from rag.retrieve import RetrievedContext


class GenerationService(Protocol):
    """
    The interface for the generation service. Responsible for generating the response
    given the input query and the retrieved contexts.
    """

    async def augmented_generation(
        self, query: "InputQuery", context: list["RetrievedContext"]
    ) -> AsyncGenerator[tuple[str, int | None], None]:
        """Answers the user's query with the retrieved context.
        Requires that you already have the context retrieved from the `RetrievalService`.

        Args:
            query (InputQuery): The input query. Contains the user's question, and optionally,
                the previous context and session ID.
            context (list[RetrievedContext]): The list of retrieved contexts. Each one contains
                the distance, file name, repository name, path in the repository, extension, and URL.

        Returns:
            (tuple[str, int]): The response generated by the model and the number of tokens spent.
        """
        ...

    def get_chat_model_name(self) -> str:
        """Returns the name of the chat model used for generation. Needed for tracking the token spend
           per model. Each model has a different token cost, e.g., the embedding model is typically cheaper
           than the generation model.


        Returns:
            (str): The name of the chat model used for generation.
        """
        ...


class PreviousQAs(BaseModel):
    """
    A Pydantic model for the previous question-answer pairs. This is used to provide the model with
    additional context from previous interactions. It is a pydantic model because it is client
    facing and is used to validate the input query. This model is used in the `InputQuery` model.

    Fields:
        question (str): A previously asked question asked by the user.
        answer (str): A previously received answer provided by the assistant.
    """

    question: str
    answer: str


class InputQuery(BaseModel):
    """
    A Pydantic model for the input query. This class is client facing and is used to validate the input query.
    The first question in the conversation will not have any previous context and will not have a session ID.
    The subsequent questions will have a session ID and previous context. The previous context is a list of
    question-answer pairs from the previous interactions. The session ID is used to track the token spend for
    the given session.

    If the session ID is provided, the previous context must also be provided otherwise a `ValueError` is raised.

    Raises:
        (ValueError): If the session ID is provided but the previous context is not provided or vice versa.
    """

    query: str
    previous_context: Optional[list[PreviousQAs]] = None
    session_id: Optional[str] = None

    def previous_context_to_dict(self) -> list[dict[str, str]]:
        """
        Transforms the previous context from a list of `PreviousQAs` to a list of dictionaries.
        This is the exact format that OpenAI's SDK expects for its completion API.

        Returns:
            list[dict[str, str]]: The previous context as a list of dictionaries.
        """
        res = []
        if self.previous_context:
            for qa in self.previous_context:
                res.append({"role": "user", "content": qa.question})
                res.append({"role": "assistant", "content": qa.answer})
        return res

    @model_validator(mode="after")
    def _validate_previous_context(self) -> Self:
        """
        Validates the input query. Ensures that the session ID is provided if the previous context is provided
        and vice versa.

        Raises:
            (ValueError): If the session ID is provided but the previous context is not provided or vice versa.

        """
        if self.session_id and not self.previous_context:
            raise ValueError(
                "Previous context must be provided if session_id is present."
            )
        elif not self.session_id and self.previous_context:
            raise ValueError(
                "Session ID must be provided if previous context is present."
            )
        return self


@dataclass(frozen=True, slots=True)
class OpenAIGenerationService(GenerationService):
    """
    A class that performs text generation using OpenAI's API. The class is responsible for generating
    the response given the input query and the retrieved contexts. The class is a wrapper around OpenAI's
    SDK and provides a more testable and maintainable interface. It implements the `GenerationService` interface.

    Args:
        client (AsyncOpenAI): The OpenAI client used for text generation.
            Relies on the `OPENAI_EMBEDDING_API_KEY` environment variable.
        chat_model (str): The name of the chat model used for text generation.
            Can be set with the `CHAT_MODEL` environment variable.
        system_prompt (str): The system prompt used for text generation.
            Can be set with the `SYSTEM_PROMPT` environment variable.
    """

    client: AsyncOpenAI
    chat_model: str
    system_prompt: str

    async def augmented_generation(
        self, query: InputQuery, context: list[RetrievedContext]
    ) -> AsyncGenerator[tuple[str, int | None], None]:
        """
        Answers the user's query with the retrieved context. Requires that you already have the context
        retrieved from the `RetrievalService`.

        Args:
            query (InputQuery): The input query. Contains the user's question, and optionally,
                the previous context and session ID.
            context (list[RetrievedContext]): The list of retrieved contexts. Each one contains
                the distance, file name, repository name, path in the repository, extension, and URL.

        Returns:
            (tuple[str, int]): The response generated by the model and the number of tokens spent.
        """
        ctx = await asyncio.gather(*[c.to_context() for c in context])
        sources = self.add_sources(context)
        model_input = self._create_model_input(query, ctx)
        with map_errors():
            stream = await self.client.chat.completions.create(
                model=self.chat_model,
                stream=True,
                messages=model_input,
                stream_options={"include_usage": True},
            )
            async for chunk in stream:
                yield self._parse_chunk(chunk, sources)

    def _parse_chunk(
        self, chunk: ChatCompletionChunk, sources: str
    ) -> tuple[str, int | None]:
        """Parses the chunk and returns the content. The chunk is a part of the response generated by the model.

        Args:
            chunk (ChatCompletionChunk): The chunk to parse.

        Returns:
            (str): The content of the chunk.
        """
        if not chunk.choices:
            usage = chunk.usage.total_tokens if chunk.usage else None
            return sources, usage

        return chunk.choices[0].delta.content or "", None

    def get_chat_model_name(self) -> str:
        """Returns the name of the chat model used for generation. Needed for tracking the token spend
            per model. Each model has a different token cost, e.g., the embedding model is typically cheaper
            than the generation model.

        Returns:
            (str): The name of the chat model used for generation.
        """
        return self.chat_model

    def _create_model_input(
        self, input: InputQuery, ctx: list[str]
    ) -> list[ChatCompletionMessageParam]:
        """Creates the model input for the generation API. The model input is a list of dictionaries."""
        query_with_ctx = f"""The user's question is {input.query}.
        You have access to additional context in a list of code files: {ctx}"""

        previous_qas = input.previous_context_to_dict()

        model_input = [{"role": "system", "content": self.system_prompt}]
        model_input.extend(previous_qas)
        model_input.append({"role": "user", "content": query_with_ctx})
        model_input = cast(list[ChatCompletionMessageParam], model_input)
        return model_input

    def add_sources(self, retrieved: list[RetrievedContext]) -> str:
        """
        Adds the sources to the answer. The sources are the list of retrieved contexts.
        The sources are added as an HTML section at the end of the answer.
        Args:
            answer (str): The answer generated by the model.
            retrieved (list[RetrievedContext]): The list of retrieved contexts.
        Returns:
            (str): The answer with the sources added as an HTML section at the end.
        """
        sources = [
            f"<li>{escape(r.file_name)} in {escape(r.repository_name)}, <a href={escape(r.url)}>source.</a></li>"
            for r in retrieved
        ]
        return f"""<section id="sources">To answer this question, I used the following sources:
            <ul>{''.join(sources)}</ul></section>"""
