import uuid
from errors import MaximumSpendError
from rag.retrieve import EmbeddingService, RemainingSpend, RetrievedContext
from rag.generation import GenerationService, InputQuery
from rag.retrieve import RetrievalService
from dataclasses import dataclass
from typing import AsyncGenerator
from datetime import date


@dataclass(frozen=True)
class RetrievalAugmentedGeneration:
    """
    Class that performs retrieval-augmented generation given an input query and k value.

    Args:
        embedding_service: The embedding service used for text embedding.
        retrieval_service: The retrieval service used for context retrieval.
        generation_service: The generation service used for text generation.
        max_spend: The maximum spend limit for the retrieval-augmented generation.
        date (datetime.date): The date of the retrieval-augmented generation.
    """

    embedding_service: "EmbeddingService"
    retrieval_service: "RetrievalService"
    generation_service: "GenerationService"
    max_spend: float
    date: date

    async def retrieval_augmented_generation(
        self,
        input: "InputQuery",
        k: int,
        id: str,
    ) -> AsyncGenerator[str, None]:
        """
        Performs retrieval-augmented generation given an input query and k value.
        The method enforces the spend limit, validates the session ID, retrieves the top k contexts,

        Args:
            input (InputQuery): The input query. Contains the user's question, and optionally,
                the previous context and session ID.
            k (int): The number of contexts to retrieve.

        Returns:
            (RAGResponse): The response generated by the model and the session ID.

        Raises:
            (MaximumSpendError): If the current spend is greater than or equal to the maximum spend limit.
        """
        await self._enforce_spend_limit()
        embed_model = self.embedding_service.get_embed_model_name()

        retrieved, tokens_spent = await self._retrieve_top_k(input, k)
        await self.retrieval_service.store_token_spent(id, tokens_spent, embed_model)

        model = self.generation_service.get_chat_model_name()
        chunk_stream = self.generation_service.augmented_generation(input, retrieved)
        async for chunk, tokens in chunk_stream:
            if tokens:
                await self.retrieval_service.store_token_spent(id, tokens, model)

            yield chunk

    async def remaining_spend(self) -> "RemainingSpend":
        """

        Calculates the remaining spend based on the current spend and the maximum spend limit.
        The spend is capped at 0.

        Returns:
            (RemainingSpend): The remaining spend.
        """
        current_spend = await self.retrieval_service.get_current_spend(self.date)
        remaining = round(self.max_spend - current_spend, 2)
        remaining = max(remaining, 0)
        return RemainingSpend(remaining)

    async def _enforce_spend_limit(self) -> None:
        """

        Enforces the spend limit by checking the current spend against the maximum spend limit.
        If the current spend is greater than or equal to the maximum spend limit, raises a `MaximumSpendError`.

        Raises:
            (MaximumSpendError): If the current spend is greater than or equal to the maximum spend limit.

        """
        current_spend = await self.retrieval_service.get_current_spend(self.date)
        if current_spend >= self.max_spend:
            raise MaximumSpendError()

    async def validate_and_assign_session_id(self, input: "InputQuery") -> str:
        """

        Validates the session ID if provided, otherwise generates a new session ID.
        This method ensures that the session ID is valid and exists in the database.
        This is necessary to track the token spend for the given session.

        Args:
            input (InputQuery): The input query. Contains the user's question, and optionally,
                the previous context and session ID.

        Returns:
            (str): The session ID.
        """
        if input.session_id:
            await self.retrieval_service.validate_session_id(input.session_id)
            session_id = input.session_id
        else:
            session_id = str(uuid.uuid4())
        return session_id

    async def _retrieve_top_k(
        self, input: "InputQuery", k: int
    ) -> tuple[list["RetrievedContext"], int]:
        """
            embeds the input query and retrieves the top k contexts based on the embedded query.


        Returns:
            (tuple[list[RetrievedContext], int]): A tuple containing the list of retrieved contexts
                and the number of tokens spent. see `RetrievedContext` for more information.
        """
        result = await self.embedding_service.embed(input.query)
        tokens_spent = result.token_count
        return (await self.retrieval_service.retrieve_top_k(result, k), tokens_spent)
