name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker compose -f compose.backend.yml -f compose.backend.override.yml build --push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: copy compose files
        run: scp -o StrictHostKeyChecking=no compose.backend.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/chatgitpt

      - name: Deploy to server
        run: ssh -o StrictHostKeyChecking=accept-new ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd ~/chatgitpt && docker compose -f compose.backend.yml --env-file .env up -d --pull always && rm compose.backend.yml'
